### ISSUE TITLE
App is hung over

### ISSUE THREAD

**Issue by Gamvu** [KyberNetwork/KyberWallet#490] opened 2018-03-01 06:09 UTC
- App is hung over; some buttons don't work (Exist, Exchange); rate keeps loading; Unable to change coin in both source and target pane.
- Configuration: Win 10 - 64 bit, Google browser. Firefox (happen to MetaMask).
- Happen to MetaMask, Trezor, Json and Ledger.
- Reproducible: Sometimes.

**Comment by andrewsource147** [comment] 2018-03-03 03:59
Caused by user input "." Fixed in notify_dropdown

**Closed by andrewsource147** 2018-03-03 03:59 UTC
