### ISSUE TITLE
Unsuccessful Transaction Still Displayed as a Successful Transasction on Wallet

### ISSUE THREAD

**Issue by hahahaha5** [KyberNetwork/KyberWallet#97] opened 2017-09-08 06:10 UTC
![1](https://user-images.githubusercontent.com/30520555/30198252-486784fe-949f-11e7-953c-3e5e5059962d.png)
![2](https://user-images.githubusercontent.com/30520555/30198259-4f40d280-949f-11e7-935d-758e7200433d.png)

as shown on etherscan, the transaction wasn't successful... yet, it says successful on wallet

**Comment by andrewsource147** [comment] 2017-09-30 07:01
I've tested many times, and it always show transaction unsuccessfully on wallet
![screencapture-localhost-3000-1506754536400](https://user-images.githubusercontent.com/31321699/31043521-835117ca-a5e7-11e7-85f0-579585b6e356.png)
![screencapture-kovan-etherscan-io-tx-0x0c33ad8c409b91dd353bccac73058cd54ccc474a55ae7e82366520f2391759ba-1506754548549](https://user-images.githubusercontent.com/31321699/31043522-84c2ef02-a5e7-11e7-9870-faea33415e02.png)

@hahahaha5 Could you pull master and test this issue again?

**Comment by tranvictor** [comment] 2017-10-09 16:48
The reason for this issue might be etherscan's kovan fork back then. I'm going to close this issue, if you can still see it happening, please reopen it with steps to reproduce the error.

**Closed by tranvictor** 2017-10-09 16:48 UTC
